name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: '8.0'

    - name: Install dependencies
      run: |
        cd backend
        npm ci

    - name: Set environment variables
      run: |
        echo "MONGO_URI=mongodb://localhost:27017/defendxstore" >> $GITHUB_ENV
        echo "SERVER_PORT=5000" >> $GITHUB_ENV
        echo "JWT_SECRET=jwtsecret" >> $GITHUB_ENV
        echo "ENVIRONMENT=test" >> $GITHUB_ENV

    - name: Run tests
      run: |
        cd backend
        npm test
